### ISSUE TITLE
intendedAt not working on heroku

### ISSUE THREAD

**Issue by rmbrich** [percolatestudio/meteor-synced-cron#22] opened 2014-10-25 14:48 UTC
Say I have two servers running the same code base, and I have a SyncedCron job set up to run every 2 hours. Will it run on both servers at the same time? Or will only one server execute the job?

Ideally, I would like the job to be only executed once (twice would be redundant). Whichever server "gets to it first" would run it and the other one wouldn't need to.

**Comment by andrejsm** [comment] 2015-05-18 11:52
2 dynos on Heroku runs every job 2 times. Using same database. Any suggestions how to avoid that?

**Comment by andrejsm** [comment] 2015-05-18 13:46
Every dyno registers different `intendedAt` times, e.g. `2015-05-18 13:40:00.501Z` and `2015-05-18 13:40:00.958Z` and that's why uniq index fails. Probably a hook to set precision of the time would be a good enough solution?

**Comment by zol** [comment] 2015-05-18 15:49
Interesting, thanks for reporting that @andrejsm . I wonder why `later.js` behaves differently on heroku. We'll look into this.

**Comment by andrejsm** [comment] 2015-05-19 07:44
The problem is caused by `later.parse.cron`. Switching to `later.parse.text` fixed the problem.
See reproduction here http://jsbin.com/xuwuhoyobo/1/watch?js,console

**Comment by zol** [comment] 2015-09-14 21:43
This should also be fixed in 6b19524adf4368ef9272ca36a5377835c1720198

**Closed by zol** 2015-09-14 21:43 UTC
Labels: bug
